name: scada_consumer

services:
  scada_consumer:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - KAFKA_CONSUMER_TOPIC
      - KAFKA_CONSUMER_GROUP_ID
      - KAFKA_BROKERS
      - KAFKA_SECURITY_PROTOCOL
      - KAFKA_SASL_MECHANISM
      - KAFKA_SASL_PLAIN_USERNAME
      - KAFKA_SASL_PLAIN_PASSWORD
      - POSTGRES_DB_LOGIN
      - POSTGRES_DB_PASSWORD
      - POSTGRES_DB_HOST
      - POSTGRES_DB_PORT
      - POSTGRES_DB_NAME
      - POSTGRESQL_URL=postgres://${POSTGRES_DB_LOGIN}:${POSTGRES_DB_PASSWORD}@${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}?sslmode=require
      - POSTGRES_MAX_CONNECTIONS
      - RABBITMQ_URL
      - RABBITMQ_CONSUMER_QUEUE
      - RABBITMQ_CONSUMER_TAG
    volumes:
      - ../pkg:/code/pkg
      - ../cmd:/code/cmd
      - ../internal:/code/internal

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.13.6-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "pYEDBqnMLoWWE"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 3
