services:
  lers:
    container_name: lers
    restart: no
    profiles: ["sync"]
    build:
      context: ../
      dockerfile: synchronizer.Dockerfile
    environment:
      POSTGRESQL_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${LERS_POSTGRES_DB_NAME}?sslmode=require
      POSTGRES_MAX_CONNECTIONS: 1
    # volumes:
    #   - ../pkg:/code/pkg
    #   - ../cmd:/code/cmd
    #   - ../internal:/code/internal
