export ZULU__POSTGRES_DB_LOGIN='zulu_admin'
export ZULU__POSTGRES_DB_PASSWORD='aN*HRPP723Z89ju'
export ZULU__POSTGRES_DB_HOST='zulu'
export ZULU__POSTGRES_DB_PORT=5434
export ZULU__POSTGRES_DB_NAME='zulu'
export ZULU__MAX_CONNECTIONS=1
export ZULU__CONNECTION_IDLE_TIME_SEC=10

export ZULU_SERVICE_POSTGRESQL_URL="postgres://${ZULU__POSTGRES_DB_LOGIN}:${ZULU__POSTGRES_DB_PASSWORD}@${ZULU__POSTGRES_DB_HOST}:${ZULU__POSTGRES_DB_PORT}/${ZULU__POSTGRES_DB_NAME}?sslmode=disable"

export ZULU__HTTP_HOST='0.0.0.0'
export ZULU__HTTP_PORT=8004
# Заменить на GIN_MODE=release во время деплоя
export GIN_MODE=debug