export PYTHONPATH=$PWD:$PWD/src:$PWD/src/
export CORE__APP_HOST=0.0.0.0
export CORE__APP_PORT=8002
export LOGGING_LEVEL=20
export DEBUG=1

export CORE__POSTGRES_DB_LOGIN='user'
export CORE__POSTGRES_DB_PASSWORD='pass'
export CORE__POSTGRES_DB_HOST='db'
export CORE__POSTGRES_DB_PORT=5432
export CORE__POSTGRES_DB_NAME='root'
export CORE__SQLALCHEMY_ECHO=False
export CORE__SQLALCHEMY_POOL_SIZE=5

