name: zulu_updater
version: "3.9"

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ELEM_ID
      - ROOT_CONNECTION_IDLE_TIME_SEC
      - ROOT_POSTGRES_MAX_CONNECTIONS
      - ROOT_POSTGRESQL_URL
      - WEATHER_BASE_URL
      - ZULU_BASE_URL
      - ZULU_CONNECTION_IDLE_TIME_SEC
      - ZULU_LAYER
      - ZULU_POSTGRES_MAX_CONNECTIONS
      - ZULU_POSTGRES_DB_LOGIN
      - ZULU_POSTGRES_DB_PASSWORD
      - ZULU_POSTGRES_DB_HOST
      - ZULU_POSTGRES_DB_PORT
      - ZULU_POSTGRES_DB_NAME
      - ZULU_POSTGRESQL_URL="postgres://${ZULU_POSTGRES_DB_LOGIN}:${ZULU_POSTGRES_DB_PASSWORD}@${ZULU_POSTGRES_DB_HOST}:${ZULU_POSTGRES_DB_PORT}/${ZULU_POSTGRES_DB_NAME}?sslmode=verify-ca;
      - ROOT_POSTGRES_DB_LOGIN
      - ROOT_POSTGRES_DB_PASSWORD
      - ROOT_POSTGRES_DB_HOST
      - ROOT_POSTGRES_DB_PORT
      - ROOT_POSTGRES_DB_NAME
      - ROOT_POSTGRESQL_URL="postgres://${ROOT_POSTGRES_DB_LOGIN}:${ROOT_POSTGRES_DB_PASSWORD}@${ROOT_POSTGRES_DB_HOST}:${ROOT_POSTGRES_DB_PORT}/${ROOT_POSTGRES_DB_NAME}?sslmode=verify-ca;
      - ZULU_TOKEN