version: "3.9"

services:
  app:
    build:
      context: ../
      dockerfile: Handle.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB_LOGIN
      - POSTGRES_DB_PASSWORD
      - POSTGRES_DB_HOST
      - POSTGRES_DB_PORT
      - POSTGRES_DB_NAME
      - MAX_CONNECTIONS
      - CONNECTION_IDLE_TIME_SEC
      - CHECK_GAP_SECONDS
      - WEATHER_STATION_BASE_URL
      - USER_SERVICE_POSTGRESQL_URL="postgres://${POSTGRES_DB_LOGIN}:${POSTGRES_DB_PASSWORD}@${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}?sslmode=disable"
