services:
  wsd-collector-main:
    container_name: wsd-collector-main
    restart: no
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      CHECK_FAILED_TIME_GAP_SECONDS: 14400
      CHECK_GAP_SECONDS: 120
      CONNECTION_IDLE_TIME_SEC: 100000
      FORECAST_API_TOKEN: ${FORECAST_API_TOKEN}
      FORECAST_BASE_URL: https://api.openweathermap.org
      NETWORK_PROTOCOL: http
      POSTGRES_MAX_CONNECTIONS: 100
      POSTGRESQL_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}?sslmode=require
      WEATHER_STATION_BASE_URL: ${WEATHER_STATION_BASE_URL}
