export POSTGRES_DB_LOGIN='scada_admin'
export POSTGRES_DB_PASSWORD='scada_pass'
export POSTGRES_DB_HOST='user_db'
export POSTGRES_DB_PORT=5434
export POSTGRES_DB_NAME='user_db'
export MAX_CONNECTIONS=1
export CONNECTION_IDLE_TIME_SEC=10
export CHECK_GAP_SECONDS=120;
export CHECK_FAILED_TIME_GAP_SECONDS=14400
export WEATHER_STATION_BASE_URL='https://94.25.30.59:3000'

export USER_SERVICE_POSTGRESQL_URL="postgres://${POSTGRES_DB_LOGIN}:${POSTGRES_DB_PASSWORD}@${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}?sslmode=disable"


